# Site settings
# These are used to personalize your new site.
title: Evan C. Hill # your name here
logo: "/images/EvanNewPicForLinkedIn.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Arts in Applied Computing: Business Concentration (class of 2025)
  <br /><br />
  <a href="https://docs.google.com/document/d/1T2yQ-vBleAr3YU43ZBO6acI58iAVp9m8/edit?usp=sharing&ouid=100852645830968979486&rtpof=true&sd=true">View My Resume</a>
  <br /><br />
  <a href="www.linkedin.com/in/evan-hill-b42b0829a">View My LinkedIn Profile</a>
repository: "echill76/echill76.github.io"
github_username:  echill76 # update with your username
google_analytics: G-H4806PGWRM # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

